### PR TITLE
Bump up to v0.6.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍
Just a minor comment.
Does the next version will add a new feature? It's 0.6.0. Not 0.5.6.

**Comment by dmikurube** [comment]
May not be a new feature, but it will require Gradle 7.6 at least.

**Comment by hiroyuki-sato** [comment]
I Got it. Thanks!

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
