### PR TITLE
Update README.md for v0.4.1

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
What do you think to add a description of the following configuration?
(`generateRubyCode`, `into` and `dependencies`)

```java
gem {
    // snip

    generateRubyCode = false
    into("lib/embulk/parser/") {
      from "lib/embulk/parser/jsonpath.rb"
    }
    into("lib/embulk/guess/") {
      from "lib/embulk/guess/jsonpath.rb"
    }
    dependencies = [
      "'jsonpath', ['~> 0.5']",
      "'json', ['~> 2.0']"
    ]
}
```

**Comment by hiroyuki-sato** [comment]
The `generateRubyCode` may not use many plugin developers.
Basically, I think this option use by plugin that implement guess feature.

I roughly checked that how many plugins implement guess feature.
Around twelve plugins implement guess. two plugins is mine.

Less than 10.

```
for i in `ls */lib/*/guess/*.rb` ; do l=$( grep -v '^ *#' $i | wc -l ); if [ $l -gt 10 ] ; then echo "$i: $l" ; fi ; done
embulk-input-jira/lib/embulk/guess/jira.rb:       22
embulk-input-zendesk/lib/embulk/guess/zendesk.rb:       21
embulk-parser-fluentd_out_file/lib/embulk/guess/fluentd_out_file.rb:       92
embulk-parser-joni_regexp/lib/embulk/guess/joni_regexp.rb:       27
embulk-parser-jsonl/lib/embulk/guess/jsonl.rb:       33
embulk-parser-jsonline/lib/embulk/guess/jsonl.rb:       30
embulk-parser-jsonpath/lib/embulk/guess/jsonpath.rb:       31
embulk-parser-ltsv/lib/embulk/guess/ltsv.rb:       53
embulk-parser-msgpack/lib/embulk/guess/msgpack.rb:       88
embulk-parser-query_string/lib/embulk/guess/query_string.rb:       44
embulk-parser-regex/lib/embulk/guess/regex.rb:      135
```

**Comment by dmikurube** [comment]
I basically don't think it would be a widely-used feature, and I don't want it to be used widely. Let us keep it undocumented.

**Comment by hiroyuki-sato** [comment]
OK, Thanks!

**Review by shroman — APPROVED** [review]
lgtm

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
