### PR TITLE
Configure Maven repositories to build the Gradle plugin

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Just a small build.gradle change. Can you have a look?

### CODE REVIEW

**Review by muga — COMMENTED** [review]
Can you tell me why `mavenLocal` is still necessary?

**Comment by dmikurube** [comment]
It was sometimes needed during the development. May not be needed now, though.

**Review by muga — APPROVED** [review]
Understand. If you still want to use `mavenLocal`, I think that it's better to add comment like "for development"  or something. Otherwise, please remove it when you can.

**Comment by dmikurube** [comment]
Thanks, but okay, it's not required now. Let me close this. :)

**Pull request closed without merging**
